[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#080c14"
secondaryBackgroundColor = "#0a0f1a"
textColor = "#c9d1d9"
